


spring:
    freemarker:
        template-loader-path: classpath:/templates/
        prefer-file-system-access: false

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false


